# Generated by Django 5.2.3 on 2025-07-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            (
                                "logo",
                                "Logo (Recommended: 512x512, PNG with transparency)",
                            ),
                            ("icon", "Icon (Recommended: 64x64 or 128x128, PNG)"),
                            ("banner", "Banner (Recommended: 1920x480, JPG/PNG)"),
                            ("thumbnail", "Thumbnail (Recommended: 600x900, JPG)"),
                            ("hero", "Hero Image (Recommended: 1920x1080, JPG)"),
                            ("screenshot", "Screenshot (Recommended: 1920x1080, JPG)"),
                            ("gallery", "Gallery Image (Any size, JPG/PNG)"),
                            ("other", "Other (Specify in custom type field)"),
                        ],
                        help_text="What type of image is this?",
                        max_length=100,
                    ),
                ),
                (
                    "custom_type",
                    models.CharField(
                        blank=True,
                        help_text='Custom image type if "Other" is selected above',
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The image file",
                        upload_to="essential_extensions/images/",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/caption for the image",
                        max_length=100,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility (auto-generated if empty)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the image"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers shown first)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this image prominently"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Extension",
                "verbose_name_plural": "Image Extensions",
                "ordering": ["image_type", "order", "-is_featured", "id"],
            },
        ),
        migrations.CreateModel(
            name="SubdomainRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "subdomain",
                    models.CharField(
                        help_text="The subdomain (e.g., 'gamex' for gamex.example.com)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "redirect_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Redirect"),
                            ("path_preserve", "Path Preserving Redirect"),
                        ],
                        default="full",
                        help_text="Full: redirect to specific path. Path Preserving: keep the same path on main domain.",
                        max_length=20,
                    ),
                ),
                (
                    "redirect_path",
                    models.CharField(
                        blank=True,
                        help_text="For Full Redirect: the path to redirect to (e.g., '/game/game-x/'). For Path Preserving: leave blank.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this redirect is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subdomain Redirect",
                "verbose_name_plural": "Subdomain Redirects",
                "ordering": ["subdomain"],
            },
        ),
        migrations.AddIndex(
            model_name="imageextension",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="essential_e_content_07bf73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imageextension",
            index=models.Index(
                fields=["image_type"], name="essential_e_image_t_ba6fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imageextension",
            index=models.Index(
                fields=["is_featured"], name="essential_e_is_feat_23c84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subdomainredirect",
            index=models.Index(
                fields=["subdomain"], name="essential_e_subdoma_67b0e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subdomainredirect",
            index=models.Index(
                fields=["is_active"], name="essential_e_is_acti_225bae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subdomainredirect",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="essential_e_content_94e820_idx",
            ),
        ),
    ]
